### ISSUE TITLE
Base122 TestVectors

### ISSUE THREAD

**Issue by patrickfav** [kevinAlbs/Base122#5]
Hi Kevin,

Im trying to write a java port of Base122 and wonder if you could provide some "official" test vectors so I could test my encoder/decoder against it? Including most of the special cases (of which you probably know what they are)

**Comment by kevinAlbs** [comment]
Hi Patrick,

Thank you for your interest, I look forward to seeing the port! I don't have "official" test vectors, but there's only a few corner cases to watch out for.

## Illegal characters get encoded/decoded correctly

Illegal inputs get encoded as: 110sss1x 10xxxxxx, where s represents a number 0-5. The numbers of each illegal input are as follows:

0 = null (0000000)
1 = newline (0001010)
2 = carriage return (0001101)
3 = double quote (0100010)
4 = ampersand (0100110)
5 = backslash (1011100)

E.g. an input of 0000000x xxxxxxyy encodes to 1100001x 10xxxxxx ...

## The last character is decoded correctly
The last byte(s) of encoded data are a special case.

When decoding, suppose the last byte is a single byte. It can represent 1-7 bits of input data. So if there are extra bits encoded, we know to round down to the nearest byte to correctly decode.

E.g. suppose the encoded data is

01010101 01000000

When decoding, we know that the data is just one byte 10101011, and that the remaining 0 bits in the second byte are just "padding". We can always round down if the last character is a single byte, since it only encodes 7 bits maximum.

However, if the last character is a two byte character, is may encode 1 to 14 bits of data. This is problematic, since if we've already decoded 7 bits of information, and then we reach the last two byte character, we need to distinigush if we should decode just 1 bit to get one byte, or 9 bits to get two.

To solve this, if the last character is a two byte character and it encodes <= 7 bits of data, then it has the form

1101111x 10xxxxxx where the x bits are the data.

Otherwise, it encodes > 7 bits of data, so we can use the normal form

110sss1x 10xxxxxx

So I'd recommend testing that cases where the last character is a two byte character decodes correctly.

## Testing with Files
When writing the article, in the process I encoded/decoded thousands of images. Just visually checking them helped me discover bugs in the encoding itself (e.g. I did not realize that the & should be illegal at first, because I had forgotten that &amp; etc. are escapes in HTML).

To test the implementation, it is testing that encoding and decoding files returns the original input is an easy and effective test.

You can also refer to the current tests here https://github.com/kevinAlbs/Base122/blob/master/test/testAll.js

It contains simple encoding/decoding tests, testing of illegal characters, testing of the trailing byte, as well as testing on files.

**Comment by kevinAlbs** [comment]
Forgot to close this. Patrick feel free to open another issue if there's a need.
